name: Binar Music
favicon: null
layout_spectrum: 0.60779
typography_spectrum: 0.61395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5c3e04'
    - '#868621'
    - '#e8ea6c'
    - '#840c0a'
  brandStrength: 0.125
  lightness: 0.4008848743978888
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
